apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: homepage
  name: homepage
spec:
  type: NodePort
  ports:
  - name: "web"
    port: 3000
    targetPort: 3000
    nodePort: 30900
  selector:
    io.kompose.service: homepage
status:
  loadBalancer: {}
