apiVersion: v1
kind: Deployment
metadata:
  name: adminer-lamp
  namespace: test-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer-lamp
  template:
    metaData:
      labels:
        app: adminer-lamp
    spec:
      containers:
      - name: adminer-lamp
        image: adminer:latest
        ports:
      - containerPort: 8080
      volumeMounts:
        - name: adminer-lamp-storage
          mountPath: /var/www/html
      volume:
      - name: adminer-lamp-storage
        persistentVolumeClaim: 
          claimName: adminer-lamp-pvc
