apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-lamp
  template:
    metadata:
      labels:
        app: mariadb-lamp
    spec:
      containers:
      - name: mariadb-lamp
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-lamp-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-lamp-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-lamp-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-lamp-secret
              key:  MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          volumeMounts:
            - name: mariadb-lamp-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-lamp-storage
          persistentVolumeClaim:
            claimName: mariadb-lamp-pvc
          
