apiVersion: v1
kind: Deployment
metadata:
  name: mariadb-lamp
spec:
  replicas: 1
  slector:
    matchLabels:
      app: mariadb-lamp
  template:
    metadata:
      labels:
        app: mariadb-lamp
    spec:
      containers:
      - name: mariadb-lamp
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-lamp-secret
              key: MYSQL_ROOT_PASSWORD

