apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: warden
  name: warden
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: warden
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: warden
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: vaultwarden-env
          image: docker.io/vaultwarden/server:latest
          name: vaultwarden
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
