version: '3.8'
services:
  warden:
    container_name: vaultwarden
    image: docker.io/vaultwarden/server:latest
    ports:
      - 8089:80
    env_file:
      - .env
    volumes:
      - ./.vw-data:/data
    restart: unless-stopped
    networks:
      - warden
  
networks:
  warden:
    driver: bridge
